# Generated by Django 6.0.5 on 2026-06-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_solicitud_usuario_alter_maquina_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
