# Generated by Django 6.0.5 on 2026-06-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_maquina_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
