# Generated by Django 6.0.5 on 2026-06-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_maquina_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.maquina'),
        ),
    ]
