# Generated by Django 6.0.5 on 2026-06-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_solicitud_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('usuario', 'Usuario')], max_length=20),
        ),
    ]
