# Generated by Django 6.0.5 on 2026-06-24 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_usuario_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.solicitud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.usuario')),
            ],
            options={
                'db_table': 'seguimiento_ticket',
            },
        ),
    ]
