# Generated by Django 6.0.5 on 2026-06-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_seguimientoticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.usuario'),
        ),
    ]
