# Generated by Django 6.0.5 on 2026-06-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_solicitud_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
