# Generated by Django 6.0.5 on 2026-06-25 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_maquina_activo_usuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.maquina'),
        ),
        migrations.CreateModel(
            name='MensajeSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('tecnico', 'Técnico'), ('lozai', 'LozAI')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.sesion')),
            ],
            options={
                'db_table': 'mensaje_sesion',
            },
        ),
    ]
